### PR TITLE
Use JobApplicationsComponent for preview page

### LINKED ISSUE #368: [BUG]: Use JobApplicationsComponent for preview page
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Preview component is currently copy/paste code from JobApplicationsComponent

### Expected Behavior

should just be adding in new props to JobApplicationsComponent

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Criteria for Completion

_No response_

### Anything else?

_No response_

### Code of Conduct

- [x] I've read the Code of Conduct and understand my responsibilities as a member of the jobba.help Community

### PR DESCRIPTION
**Pull request by elyseando**
# Pull Request

## Description
Removed JobApplicationsDashboardPreview component and instead added new props to JobApplicationsDashboard component.

## Related Issue

Fixes #368 

## Type of Change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] 🎨 Style update (formatting, renaming)
- [ ] ♻️ Code refactor (no functional changes)
- [ ] ⚡️ Performance improvement
- [ ] ✅ Test update
- [ ] 🔨 Build configuration update
- [ ] 🔒 Security update

## Changes Made

1. Removed JobApplicationsDashboardPreview component and instead added new props to JobApplicationsDashboard component. Added extraHeaderContent to pass the response rate card and chart.
2. 
3. 

## Testing

1. Steps to reproduce:
   - 
   - 
   - 
2. Test environment:
   - OS: 
   - Node version:
   - Browser (if applicable):

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Dependencies

- 
- 

## Database Changes

- [ ] No database changes
- [ ] Database changes included (describe below):
  - 

## API Changes

- [ ] No API changes
- [ ] API changes included (describe below):
  - 

## Performance Impact

- [ ] No performance impact
- [ ] Performance impact (describe below):
  - 

## Security Considerations

- [ ] No security implications
- [ ] Security implications considered (describe below):
  - 

## Reviewer Notes

- 
- 

## Post-Deployment Steps

- [ ] No post-deployment steps needed
- [ ] Post-deployment steps required (describe below):
  - 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the project's license.

### CODE REVIEW

File: frontend/app/dashboard/page.tsx [hunk 1]
```diff
@@ -205,11 +207,25 @@ export default function Dashboard() {
 		}
 	};
 
+	const extraHeaderContent = (
```
Comment (lnovitz) [inline frontend/app/dashboard/page.tsx:210]: I'd rename to something more descriptive

**Review by lnovitz — COMMENTED** [review]
Just a small nit on the naming but looks great otherwise :)

File: frontend/app/preview/dashboard/page.tsx [hunk 2]
```diff
@@ -146,12 +148,26 @@ export default function PreviewDashboard() {
...
+		</>
+	);
+
 	return (
 		<JobApplicationsDashboard
 			currentPage={currentPage}
 			data={data}
 			downloading={downloading}
-			extraHeader={PromoModal}
+			extraHeader={previewResponseRateContent}
```
Comment (lnovitz) [inline frontend/app/preview/dashboard/page.tsx:170]: The prop name could also be renamed

**Review by lnovitz — CHANGES_REQUESTED** [review]

File: frontend/app/preview/dashboard/page.tsx (hunk 2 above)
Comment (elyseando) [reply frontend/app/preview/dashboard/page.tsx:170]: oh oops

Comment (lnovitz) [reply frontend/app/preview/dashboard/page.tsx:170]: Nah it's my bad I wasn't specific sorry!

**Review by lnovitz — APPROVED** [review]
